//TODO: untested, generated by gpt-oss:20b
use serde::de::Deserializer;
use serde::ser::Serializer;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

#[derive(Serialize, Deserialize)]
struct WalletEntry {
    #[serde(rename = "currencyId")]
    currency_id: Uuid,
    balance: u64,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct CompleteWallet(
    #[serde(
        rename = "wallet",
        serialize_with = "serialize_wallets",
        deserialize_with = "deserialize_wallets"
    )]
    pub HashMap<Uuid, u64>,
);

fn serialize_wallets<S>(wallets: &HashMap<Uuid, u64>, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    let entries: Vec<WalletEntry> = wallets
        .iter()
        .map(|(id, bal)| WalletEntry {
            currency_id: *id,
            balance: *bal,
        })
        .collect();
    entries.serialize(serializer)
}

fn deserialize_wallets<'de, D>(deserializer: D) -> Result<HashMap<Uuid, u64>, D::Error>
where
    D: Deserializer<'de>,
{
    let entries: Vec<WalletEntry> = Vec::deserialize(deserializer)?;
    let mut map = HashMap::new();
    for entry in entries {
        map.insert(entry.currency_id, entry.balance);
    }
    Ok(map)
}
