//TODO: untested, generated by gpt-oss:20b
use crate::generate_map_to_vec_serialization;
use serde::de::Deserializer;
use serde::ser::Serializer;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct WalletEntry {
    pub balance: u64,
}

generate_map_to_vec_serialization!(wallet_serde, WalletEntry, currency_id);

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct CompleteWallet(
    #[serde(
        rename = "wallet",
        serialize_with = "wallet_serde::serialize",
        deserialize_with = "wallet_serde::deserialize"
    )]
    pub HashMap<Uuid, WalletEntry>,
);
