from typing import List, Union
from decimal import Decimal, InvalidOperation

# parse_number generated by gpt-oss: 20b
def parse_number(data: Union[int, float, str]) -> int:
    """
    Parse a numeric value and ensure it is an integer.

    - If ``data`` is an ``int``, it is returned unchanged.
    - If ``data`` is a string, it is parsed as a decimal number.
      If the parsed value is not an integer, a ``ValueError`` is raised
      (this indicates that the type expectation was wrong and a different
      implementation is required).
    - ``float`` values are rejected as they violate the integer-only contract.
    """
    if isinstance(data, int):
        return data

    if isinstance(data, float):
        raise ValueError(f"Unexpected float value: {data!r}. Expected integer.")

    if isinstance(data, str):
        try:
            d = Decimal(data)
        except InvalidOperation as exc:
            raise ValueError(f"Cannot parse numeric value from string: {data}") from exc

        if d == d.to_integral_value():
            return int(d)
        else:
            raise ValueError(f"Expected integer value, got non-integer: {data}")

    raise ValueError(f"Unsupported type for parse_number: {type(data).__name__}")


def parse_apparition_settings(settings: List[dict]) -> List[dict]:
    result = []
    for entry in settings:
        result.append({
            "interactable_uuid": entry["_clutterType"]["_uid"]["_id"],
            "weight": parse_number(entry["_weightMultiplier"]),
            "mandatory": entry["_mandatory"],  # not sure what that represent, but it seems important
        })
    return result


def parse_reward_givers(reward_givers: List[dict]) -> List[dict]:
    result = []
    for entry in reward_givers:
        result.append(parse_reward(entry["_reward"]))
    return result


def parse_reward(reward: dict) -> dict:
    items_to_reward = []
    for item_reward_entry in reward["_inventory"]["_itemsList"]:
        items_to_reward.append({
            "count": item_reward_entry["_count"],
            "template_uuid": item_reward_entry["Item"]["_uid"]["_id"]
        })
    return {
        "experience": reward["_experience"],
        "town_points": reward["_townPoints"],
        "chest_is_none": reward["_chest"]["_chestCycle"]["_uid"]["_id"] == 0, # just so the server can panic if the data is invalid
        "items_to_reward": items_to_reward
    }
